### ISSUE TITLE
Is there a timeline of supporting iOS?

### ISSUE THREAD

**Issue by ryanlin1986** [Santino-Wu/cordova-plugin-unionpay#1]
We are having a project which require both android and iOS support for unionpay, ;) Adding iOS support should help us a lot.

**Comment by Santino-Wu** [comment]
Sorry for my mistake, i forgot to remove _TODO_ list from README file.

iOS had been supported, this plugin works well in my project(both **Android** and **iOS**).

Cheers,

**Comment by ryanlin1986** [comment]
Thanks, we are already using this plugin, very cool!
